version: 0.2

phases:
  install:
    commands:
      - cd ../frontend
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
post_build:
  commands:
    - aws s3 sync build s3://$S3_BUCKET_NAME --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"